### ISSUE TITLE
help how do you convet png to 3dst

### ISSUE THREAD

**Issue by Riccardominecart** [mc-3ds-team/mc-adventure-time-mash-up-3ds-port#1]
if you can please convert this image for me thanks becaus i don't now how to use it thanks
![4J_Studios_logo](https://github.com/user-attachments/assets/c8b836a2-fc20-4df0-8e9b-440e27e94dd0)
![4J-Logo-JPEG-1](https://github.com/user-attachments/assets/4d3b4687-f004-4f87-bfab-fc7ee355e023)

**Comment by susbaconhairman** [comment]
Hello, I am sorry, but this is not the place for asking questions unrelated to the Adventure Time mash-up port.

If you would like to convert these to 3DST, here is the tool for doing so: [https://gbatemp.net/attachments/ohana3ds-zip.99223/](https://gbatemp.net/attachments/ohana3ds-zip.99223/)
The image you want to create must be flipped horizontally, and be the same resolution when you input it into the program. The file I assume you want to replace is in ```\RomFS\resourcepacks\vanilla\client\other_ocean_logo.3dst```, if you want to change the game's boot splash screen.
For more information about modding the game, please visit my Discord server: [https://discord.gg/YRGfUpPqA9](https://discord.gg/YRGfUpPqA9)
